spring:
  application:
    name: marcpascualsanchez-holaluz-hiring
  main:
    web-application-type: none
    banner-mode: "off"

fraud-detector:
  files:
    lines-by-client: 12
    csv:
      separator: ","